# Generated by Django 4.2.3 on 2023-08-28 21:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_time_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id', 'important', 'time_limit']},
        ),
        migrations.AlterField(
            model_name='task',
            name='time_limit',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 28))]),
        ),
    ]
