# Generated by Django 4.2.3 on 2023-09-11 20:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_options_alter_task_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_limit',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 11))]),
        ),
    ]
