# Generated by Django 4.2.3 on 2023-08-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_user_birthday_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='portafolio/users/user.png', null=True, upload_to='portafolio/users/'),
        ),
    ]
