# Generated by Django 4.2.3 on 2023-08-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rating_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='introduction',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
