# Generated by Django 4.2.3 on 2023-08-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_rating_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='description',
            new_name='comment',
        ),
    ]
