# Generated by Django 4.2.3 on 2023-08-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_description_rating_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='article_id',
            new_name='article',
        ),
    ]
