# Generated by Django 4.2.3 on 2023-08-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_article_id_rating_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
