# Generated by Django 4.2.3 on 2023-08-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_user_id_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
