# Generated by Django 4.2.3 on 2023-08-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_value_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(max_length=255),
        ),
    ]
